Add JsType plugin
deephaven/deephaven-plugin pull request #7
Opened 2022-09-23 22:12 UTC by devinrsmith

2022-09-26 13:33 UTC, mofojed commented
Can you give more context in the description of this PR please? What is the JsType for? How do you use it?

2022-09-26 15:39 UTC, devinrsmith commented
I'll add some pydoc - I should probably do the same for ObjectType...

2022-10-11 13:47 UTC, mofojed requested changes
Please, add some context to the PR description. How is this used? How did you test it?

2022-10-11 14:58 UTC, mofojed approved these changes

2022-10-12 16:39 UTC, niloc132 approved these changes

2022-10-12 16:43 UTC, merged